---
title: "NG_Paper_Method"
author: "Mark Lamin"
date: '2022-07-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(VIM)
library(tidyverse)
```

```{r}
#Reading data
met_dat <- read.delim("../Metabolites.txt", sep = " ")
pro_dat <- read.delim("../Proteins.txt", sep = " ")

#knn imputation
met_dat_imputed <- kNN(data = met_dat, k = 10)
pro_dat_imputed <- kNN(data = pro_dat, k = 10)

#log base 2 normalization
met_dat_imp_norm <- log2(met_dat_imputed)
pro_dat_imp_norm <- log2(pro_dat_imputed)

#excluding boolean columns
new_met <- met_dat_imp_norm[, 1:64]
new_pro <- pro_dat_imp_norm[, 1:64]
```

```{r}
#Met data first 

sigma <- 1
num_col <- length(new_met[, 1])
A <- matrix(rep(0, num_col^2), nrow = num_col)
for (i in 1:num_col) {
  for (j in 1:num_col) {
    if(i!=j){
      diff <- new_met[i, ] - new_met[j, ]
      nm <- sum(diff^2)
    A[i, j] <- exp(-nm/(2*sigma^2))
    }
  }
}

D <- matrix(rep(0, num_col^2), nrow = num_col)
for (i in 1:num_col) {
  D[i,i] <- (sum(A[i, ]))^(-0.5)
}

L <- D %*% A %*% D

ev <- eigen(L)
names(ev)

x <- ev$vectors[, 15:18]
sum(is.na(x))
nrow(x)
```

```{r}
for (i in 1:nrow(x)) {
  if((sum(x[i, ] == c(0,0)))!=4){
    my_len <- sqrt(sum((x[i, ])^2))
    x[i, ] <- x[i, ]/my_len
  }
  
}

y <- x

km.out <- kmeans(y, 4, nstart = 20)
my_clusters <- km.out$cluster
my_clusters
```

```{r}
#prcomp(dat)$x[,1:2]

ggplot(data.frame(prcomp(new_met)$x[,1:2])) + 
  geom_point(mapping = aes(x = prcomp(new_met)$x[,1],
                           y = prcomp(new_met)$x[,2],
                           col = as.factor(my_clusters)))

ggplot(data.frame(y)) + 
  geom_point(mapping = aes(x = y[,1],
                           y = y[,2],
                           col = as.factor(my_clusters)))
```

