---
title: "Imputation & Normalization"
author: "Colette Pollard"
date: '2022-07-01'
output: html_document
---
# Read data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(VIM)
library(caret)
library(beepr)
library(AppliedPredictiveModeling)
library(factoextra)

metabolites <- read.table("C:\\Users\\Colette\\Downloads\\CoSIBS\\Multi-Omics Project\\Metabolites.txt")
proteins <- read.table("C:\\Users\\Colette\\Downloads\\CoSIBS\\Multi-Omics Project\\Proteins.txt")
```

# Initial visualizations
```{r}
boxplot(metabolites, beside=T)
boxplot(metabolites[-c(1,3,4,5,10,11,12,26,33,34,36,37,39,41,49,50,54,63,64)], beside=T, outline=F)
boxplot(proteins, beside=T)
boxplot(proteins[-c(38,1,2,3,4,5,6,7,9,10,11,13,14,15,19,24,25,81,86,74,71,70,66,64,62,60,58,55,54)], beside=T, outline=F)
```

# Imputation

Assumming MCAR
Use 5 or 10 neighbors
Standard cutoff is 20% missing per column 
```{r}
#apply statement to do same function to every column or every row
missingness_m <- apply(metabolites, 2, FUN= function(x) {
  sum(is.na(x))/length(x)})
summary(missingness_m)

missingness_p <- apply(proteins, 2, FUN= function(x) {
  sum(is.na(x))/length(x)})
summary(missingness_p)

#either 5 or 10 for k (10 is pretty standard)
met_imputed <- kNN(metabolites, variable=colnames(metabolites), k=10)
prot_imputed <- kNN(proteins, variable=colnames(proteins), k=10)
```


# Log_2 Normalization
```{r}
#standardization? scaling? quantile normalization?
log_met <- log2(met_imputed)
log_prot <- log2(prot_imputed)
```

# post normalization visualization
```{r}
boxplot(log_met, beside=T)
boxplot(log_prot, beside=T)

featurePlot(x = log_met[, 1:3],
            y = log_met[, 4:6],
            plot = "pairs",
            ## Add a key at the top
            auto.key = list(columns = 6))

featurePlot(x = log_prot[, 1:3],
            y = log_prot[, 4:6],
            plot = "pairs",
            ## Add a key at the top
            auto.key = list(columns = 6))
```
# fix exponential representation
```{r}
# log_met_full <- options("scipen"=0, "digits"=7)
# log_met_full2 <- options(scipen = 999)
log_met_full <- format(log_met, scientific = FALSE)
```

# Spectral clustering
```{r}
#choose k
set.seed(123)
fviz_nbclust(df, kmeans, method = "wss")

wss <- (nrow(log_met)-1)*sum(apply(log_met,2,var))
for(i in 1:100) wss[i] <- sum(kmeans(log_met, centers=i)$withinss)
plot(1:100, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")

#compute k means
met <- kmeans(log_met, 3, nstart=30)
met$cluster
print(met)
prot <- kmeans(log_prot, 3, iter.max=10, nstart=30)
prot$cluster
print(prot)

#visualize clusters
fviz_cluster(k2, data = df)

df %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(UrbanPop, Murder, color = factor(cluster), label = state)) +
  geom_text()
```


